updated

diff --git a/dms-cli/src/main/bin/dms-docker b/dms-cli/src/main/bin/dms-docker
--- a/dms-cli/src/main/bin/dms-docker
+++ b/dms-cli/src/main/bin/dms-docker
@@ -5,6 +5,69 @@ export DOCKER_EXE=$DEFAULT_DOCKER_EXE
 export SPEC_FILENAME=spec.yaml
 export TEMP_SPEC_FILE=/tmp/$SPEC_FILENAME
 
+export DMS_HOME=$HOME/.dms
+export DMS_SPEC_FILE=$DMS_HOME/spec.yaml
+
+MIN_VERSION=19.03.00
+
+function isVersionGTE {
+	input_version=$1
+	min_version=$2
+
+	input_major_version=$(parseMajorVersion $input_version)
+	input_minor_version=$(parseMinorVersion $input_version)
+	input_patch_version=$(parsePatchVersion $input_version)
+
+	min_major_version=$(parseMajorVersion $min_version)
+	min_minor_version=$(parseMinorVersion $min_version)
+	min_patch_version=$(parsePatchVersion $min_version)
+
+	result=true
+	if [ $input_major_version -lt $min_major_version ];then
+		result=false
+	elif [ $input_major_version -eq $min_major_version ];then
+		if [ $input_minor_version -lt $min_minor_version ];then
+			result=false
+		elif [ $input_minor_version -eq $min_minor_version ];then
+			if [ $input_patch_version -lt $min_patch_version ];then
+				result=false
+			fi
+		fi
+	fi
+	echo $result
+}
+
+function parseMajorVersion {
+	echo $1 | sed 's/^\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)$/\1/g'
+}
+
+function parseMinorVersion {
+	echo $1 | sed 's/^\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)$/\2/g'
+}
+
+function parsePatchVersion {
+	echo $1 | sed 's/^\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)$/\3/g'
+}
+
+function checkDocker {
+	# check docker exists: show instructions 
+	result_output=$($DOCKER_EXE version -f '{{ .Server.Version }}' 2>&1)
+	result_code=$?
+	if [ $result_code -ne 0  ]; then
+		echo "Could not execute the docker command. Message: $result_output"
+		exit 1
+	else
+		version_result=$(isVersionGTE $result_output $MIN_VERSION)
+		if [ "$version_result" == "false" ]; then
+			echo "[ERROR]: The installed docker version $result_output is not >= $MIN_VERSION"
+			exit 1
+		fi
+	fi
+	# check its executable and has user has permissions :  docker ps -q | head -1
+	# check docker version
+}
+
+
 function setupDockerExecutable {
 	if [ ! -f $DEFAULT_DOCKER_EXE ]; then
 		result=$(whick docker)
@@ -20,40 +83,30 @@ function setupDockerExecutable {
 }
 
 function getLatestVersion {
-	echo "test"
+	echo "latest"
 }
 
 function genLatestSpec {
+	output_path=$1
 	version=$(getLatestVersion)
-	echo "version: $version" > $TEMP_SPEC_FILE
-	echo $TEMP_SPEC_FILE
+	echo "version: $version" > $output_path
 }
 
 function provisionSpec {
-	volume_name=$1
-	spec_filename=$2
+	spec_filename=$1
 
-	# Create the container to manage the volume data. It does not need to run.
-	container_id=$(docker container create -v $volume_name:/temp-volume hello-world)
-
-	# Copy the spec.yaml from the volume without running the container. 
-	# If it does not exist, generate one locally using the latest dms version and copy it to the volume
-	$(docker cp $container_id:/temp-volume/$spec_filename $TEMP_SPEC_FILE)
-	if [ $? -ne 0 ]; then
-		# echo "The file \"$spec_filename\" DOES NOT exist, creating it..."
-		new_spec_filename=$(genLatestSpec)
-		docker cp $TEMP_SPEC_FILE $container_id:/temp-volume
+	if [ ! -d $DMS_HOME ];then
+		mkdir -p $DMS_HOME
 	fi
 
-	# Destroy the container
-	docker rm $container_id > /dev/null
+	if [ ! -f $DMS_SPEC_FILE ];then
+		genLatestSpec $DMS_SPEC_FILE
+	fi
 
-	# Extract the spec version
-	read_version=$(cat $TEMP_SPEC_FILE | grep version | sed 's/.*:\s\+//')
-	rm -rf $TEMP_SPEC_FILE
+	dms_version=$(cat $DMS_SPEC_FILE | grep version | sed 's/.*:\s\+//')
 
 	# Return the version
-	echo $read_version
+	echo $dms_version
 }
 
 function main {
@@ -67,9 +120,10 @@ function main {
 	spec_filename="spec.yaml"
 
 	setupDockerExecutable
+	checkDocker
 
 	# Get dms version from spec
-	dms_version=$(provisionSpec $volume_name $spec_filename)
+	dms_version=$(provisionSpec $spec_filename)
 
 	#################################
 	# Define the docker options
